// Local assets keep technology badges independent of third-party image hosts.
export const technologyLogos = {
  'Next.js': 'nextjs.svg',
  React: 'react.svg',
  TypeScript: 'typescript.svg',
  JavaScript: 'javascript.svg',
  Tailwind: 'tailwind.svg',
  MongoDB: 'mongodb.svg',
  OpenAI: 'openai.svg',
  Vapi: 'vapi.svg',
  WebRTC: 'webrtc.svg',
  'Socket.IO': 'socketio.svg',
  'Node.js': 'nodejs.svg',
  OpenRouter: 'openrouter.svg',
  FastAPI: 'fastapi.svg',
  Twilio: 'twilio.svg',
  Docker: 'docker.svg',
  Python: 'python.svg',
  LangChain: 'langchain.svg',
  Pinecone: 'pinecone.svg',
  PineconeDB: 'pinecone.svg',
  Prisma: 'prisma.svg',
  Shadcn: 'shadcn.svg',
  Firebase: 'firebase.svg',
  'React Flow': 'reactflow.svg',
  Playwright: 'playwright.svg',
  HTTPX: 'httpx.png',
  'Beautiful Soup': 'beautifulsoup.svg',
  'JSON Schema': 'json.svg',
  PyPDF: 'pypdf.svg',
  PyTorch: 'pytorch.svg',
  Transformers: 'huggingface.svg',
  'Hugging Face Datasets': 'huggingface.svg',
  Pillow: 'pillow.svg',
  BERTScore: 'bertscore.svg',
  Gymnasium: 'gymnasium.svg',
  PyBullet: 'pybullet.svg',
  NumPy: 'numpy.svg',
  Matplotlib: 'matplotlib.svg',
  Streamlit: 'streamlit.svg',
  'SQL Server': 'sqlserver.svg',
  pyodbc: 'pyodbc.svg',
  Cheerio: 'cheerio.svg',
  JSDOM: 'jsdom.svg',
  Verilog: 'verilog.svg',
  Vivado: 'vivado.svg',
  HTML: 'html.svg',
  CSS: 'css.svg',
  Redux: 'redux.svg',
  MySQL: 'mysql.svg',
  Git: 'git.svg',
  GitHub: 'github.svg',
  'Framer Motion': 'framer.svg',
  Go: 'go.svg',
  Swift: 'swift.svg',
  Django: 'django.svg',
  'AWS Amplify': 'aws.svg',
  'A/B Testing': 'abtesting.svg',
  'React Native': 'reactnative.svg',
  Express: 'express.svg',
  'Payload CMS': 'payload.svg',
} as const

export type Technology = keyof typeof technologyLogos
